### ISSUE TITLE
http-broadcast doesn't resubscribe when mercure is restarted?

### ISSUE THREAD

**Issue by Yggdrasil** [jderusse/http-broadcast#22]
Hi jderusse, we're using http-broadcast in a Kubernetes cluster. Thanks a bunch for creating this handy utility.

**Some background**
http-broadcast is a container in our Varnish pods with one or more replicas, while mercure runs as its own pod. We use http-broadcast to broadcast BAN requests to all replicas. Applications send BAN http-requests to purge objects from Varnish cache. One of the Varnish replicas receives the request, notices the request is new (i.e. http-broadcast's HUB_GUARD_TOKEN isn't present yet in the headers) and relays it to its local http-broadcast port. http-broadcast publishes the request to the mercure service.

Mercure in turn sends the request to all its subscribers, including the server that just submitted it. All subscribers relay the request to their AGENT_ENDPOINT (i.e. their local Varnish) which detects the HUB_GUARD_TOKEN is now present and processes the BAN. When this works properly all Varnish replicas ban the objects from their cache.

We started noticing that caches weren't getting purged and my investigation revealed the following problem.

**The problem**
When the Mercure pod is killed and comes back up (which happens once or twice a day) http-broadcast doesn't appear to resubscribe, meaning http-broadcast never receives messages published after the restart or Mercure. Only restarting the http-broadcast container will cause it to resubscribe to the topic.

During the minute or so that Mercure is offline the http-broadcast container complains "`Server: Failed to push record: Post http://mercure/.well-known/mercure: dial tcp 10.0.95.14:80: connect: connection refused`" once for each request it wants to publish, as I would expect. It also logs "`runtime error: invalid memory address or nil pointer dereference`", which doesn't look like it's ok.

As soon as Mercure is back up these messages stop. I don't see Mercure receiving any messages that http-broadcast was trying to send during its downtime. http-broadcast does publish any new messages it processes _after_ Mercure is back up.

http-broadcast never appears to resubscribe to Mercure. This means that none of the message http-broadcast publishes during or after Mercure's absence get delivered by Mercure.

So I see two problems:
1. http-broadcast should resubscribe after it is able to reconnect to Mercure.
2. http-broadcast should buffer outgoing messages when Mercure is unavailable and retry them.

Do we have http-broadcast configured incorrectly or are these features that could be added?

Our http-broadcast configuration (a section of our Varnish deployment's manifest):
```
      - env:
        - name: SERVER_ADDR
          value: :6083
        - name: AGENT_ENDPOINT
          value: http://127.0.0.1:80
        - name: HUB_ENDPOINT
          value: http://mercure/.well-known/mercure
        - name: HUB_TOKEN
          value: <snip>
        - name: LOG_LEVEL
          value: debug
        - name: LOG_FORMAT
          value: json
        image: jderusse/http-broadcast:v0.1.0
```

Our mercure configuration (also a snippet from the deployment manifest):
```
      - env:
        - name: JWT_KEY
          value: <snip>
        - name: LOG_FORMAT
          value: json
        - name: DEBUG
          value: "1"
        image: dunglas/mercure:v0.8.0
```

Thanks for your help.
